### ISSUE TITLE
False positive on 1-byte text file containing a newline

### ISSUE THREAD

**Issue by andersk** [Neo23x0/Loki#99] opened 2018-02-02 01:18 UTC
I may have found the world’s smallest virus here:

```console
$ mkdir dir
$ printf '\n' > dir/newline.txt
$ python loki.py -p dir
…
[INFO] Scanning dir ...  
[ALERT] 
FILE: dir/newline.txt SCORE: 100 TYPE: UNKNOWN SIZE: 1 
FIRST_BYTES: 0a /  
MD5: 68b329da9893e34099c7d8ad5cb9c940 
SHA1: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc 
SHA256: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b CREATED: Thu Feb  1 20:15:26 2018 MODIFIED: Thu Feb  1 20:15:26 2018 ACCESSED: Thu Feb  1 20:15:30 2018 
REASON_1: Malware Hash TYPE: SHA256 HASH: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b SUBSCORE: 100 DESC: Crimeware-as-a-Service https://www.virustotal.com/en/ip-address/188.128.173.225/information/ / https://
[NOTICE] Results: 1 alerts, 0 warnings, 3 notices
[RESULT] Indicators detected!
[RESULT] Loki recommends checking the elements on Virustotal.com or Google and triage with a professional triage tool like THOR APT Scanner in corporate networks.
```

**Comment by Neo23x0** [comment] 2018-02-02 07:56
Thanks. Fixed in this commit https://github.com/Neo23x0/signature-base/commit/e1627413184270a6ea1d70d0ff67c144f04da7cc

It was caused by this OTX pulse
https://otx.alienvault.com/pulse/57e928543f5d465dafc74a78

**Closed by Neo23x0** 2018-02-02 07:56 UTC
