### ISSUE TITLE
initializing yara rule error,this is a problem,

### ISSUE THREAD

**Issue by taibaiyifeng** [Neo23x0/Loki#79] opened 2017-09-07 08:17 UTC
SyntaxError: /root/Desktop/ioc_scaner/Loki-0.24.1/./signature-base/yara/k3e9.51b9332691a31932.yara(25): invalid field name "md5"
[INFO] Initializing Yara rule apt_eqgrp_apr17.yar
Traceback (most recent call last):
  File "loki.py", line 1050, in initialize_yara_rules
    'md5': dummy
SyntaxError: /root/Desktop/ioc_scaner/Loki-0.24.1/./signature-base/yara/k3e9.17e30b0a1ee31132.yara(24): invalid field name "md5"
Traceback (most recent call last):
  File "loki.py", line 1050, in initialize_yara_rules
    'md5': dummy

this is 1050 line code
        # Test Compile
1044                             try:
1045                                 compiledRules = yara.compile(yaraRuleFile, externals={
1046                                     'filename': dummy,
1047                                     'filepath': dummy,
1048                                     'extension': dummy,
1049                                     'filetype': dummy,
1050                                     'md5': dummy
1051                                 })
1052                                 logger.log("INFO", "Initializing Yara rule %s" % file)
1053                             except Exception, e:
1054                                 traceback.print_exc()
1055                                 if logger.debug:
1056                                     sys.exit(1)
1057                                 continue

**Comment by taibaiyifeng** [comment] 2017-09-07 08:22
this is one of the rule
:~/Desktop/ioc_scaner/Loki-0.24.1# cat signature-base/yara/k3e9.17e30b0a1ee31132.yara 
import "hash"

rule k3e9_17e30b0a1ee31132
{

   meta:
     copyright="Copyright (c) 2014-2017 Support Intelligence Inc, All Rights Reserved."
     engine="saphire/1.2.2 divinorum/0.99 icewater/0.3.01"
     viz_url="http://icewater.io/en/cluster/query?h64=k3e9.17e30b0a1ee31132"
     cluster="k3e9.17e30b0a1ee31132"
     cluster_size="4 samples"
     filetype = "pe"
     tlp = "amber"
     version = "icewater foxtail"
     author = "Rick Wesson (@wessorh) rick@support-intelligence.com"
     date = "20170811"
     license = "non-commercial use only"
     family="virut virtob virux"
     md5_hashes="['c9ed55e9f982b6e1a82df68a64c4628a', 'c9ed55e9f982b6e1a82df68a64c4628a', 'e198f3cadd6a41fc4076cf648cd55ab0']"


   condition:
      filesize > 16384 and filesize < 65536
      and hash.md5(4096,1024) == "2f71af6522927f93cb15efa00c89d5db"
}

**Comment by wessorh** [comment] 2017-10-13 02:35
This happens when you don't have the openssl-dev or libssl-dev installed when you build yara. The md5 module isn't built. The error is obtuse

**Comment by Neo23x0** [comment] 2017-11-12 16:53
Yes - YARA versions 3.6.x did not provide the "hash" module in the precompiled Python packages. I removed the IceWater signatures until the problem is resolved. This issue could be fixed with the recently released version 3.7.0 of YARA, but I haven't checked it yet.

**Closed by Neo23x0** 2017-11-12 16:53 UTC
