### ISSUE TITLE
Doesn't work with cyrillic filenames (repeatedly)

### ISSUE THREAD

**Issue by jane567** [Neo23x0/Loki#56] opened 2016-12-19 08:58 UTC
Version 0.18.1 doesn't work with unicode chars in filename - such files silently ignored. This issue already has been fixed in prev version.

**Comment by Neo23x0** [comment] 2016-12-19 12:59
Bug due to the complete refactoring of the output engine. I'll check this the next weekend.

**Comment by Neo23x0** [comment] 2016-12-20 15:04
Cannot reproduce this error. Unicode characters are replaced by "?" on the command line and written aus Unicode to the .log file.
![screen shot 2016-12-20 at 16 02 56](https://cloud.githubusercontent.com/assets/2851492/21355322/d688eb06-c6cd-11e6-83e9-b85623b605e1.png)

**Comment by Neo23x0** [comment] 2016-12-20 15:05
Is it possible that Cyrillic characters appear in other attributes that get printed to the command line?

**Comment by jane567** [comment] 2016-12-20 18:07
I just add to filename-iocs filename, add such file to dir, then try to exec loki and nothing in log  ..

**Comment by jane567** [comment] 2016-12-20 18:13
I think it's not correct to write console output/log file in ascii. unicode more suitable.

**Comment by Neo23x0** [comment] 2016-12-21 16:04
Should be fixed in 0.18.2

**Closed by Neo23x0** 2016-12-21 16:04 UTC
Labels: bug
